name       : gnome-mines
version    : 3.32.0
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-mines/3.32/gnome-mines-3.32.0.tar.xz : 92e9e9b8d659bf26f25a84df61c3db944d8cdbb6e8721a9008d7b6ba8e422a8e
license    : GPL-2.0-only
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
