name       : gnome-mines
version    : 3.18.1
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-mines/3.18/gnome-mines-3.18.1.tar.xz : 96c30da79a29ac9b9fe7c9de517147c052a72d1d386a1f2a0cfb633d35405dbc
license    : GPL-2.0
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
