name       : gnome-mines
version    : 3.28.0
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-mines/3.28/gnome-mines-3.28.0.tar.xz : 6e77d79056b19c2c805250cb759e5f78711fb1b1f7250b0edaecc6ae302c859b
license    : GPL-2.0-only
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
