name       : gnome-mines
version    : 3.20.1
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-mines/3.20/gnome-mines-3.20.1.tar.xz : 5815e886d92817d4127b9e94bf63cb91e2bf371029d18efdf9f195e2400e2b3b
license    : GPL-2.0
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
