name       : gnome-mines
version    : 3.24.0
release    : 7
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-mines/3.24/gnome-mines-3.24.0.tar.xz : e663af29235a5c3f03d90f135487f57e5fd9137480dafb0ae9efc0da855602f6
license    : GPL-2.0
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
