name       : gnome-mines
version    : 3.34.0
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-mines/3.34/gnome-mines-3.34.0.tar.xz : a4f0189ef0fc45d5d5554197649f15014db82ff791ddad732e1af990b151fdea
license    : GPL-2.0-only
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
