name       : gnome-mines
version    : 3.16.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-mines/3.16/gnome-mines-3.16.1.tar.xz : 17ac2c2bd35510c8eaf2a521fe4665406cb13211942d343fe177e708ad490438
license    : GPL-2.0
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
