name       : gnome-mines
version    : '40.0'
release    : 17
source     :
    - https://download.gnome.org/sources/gnome-mines/40/gnome-mines-40.0.tar.xz : 1f79ba6c2ae4a56e5a0c23668d40f05cfcac68a2d848db1a1cf9920c779bc669
license    : GPL-2.0-only
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
