name       : gnome-mines
version    : 3.36.0
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-mines/3.36/gnome-mines-3.36.0.tar.xz : 4afe897d96c26bc8f221752e154a761a6a033197df8db0fd5879e4b77af5a354
license    : GPL-2.0-only
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
