name       : gnome-mines
version    : 3.32.2
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-mines/3.32/gnome-mines-3.32.2.tar.xz : 0f757f4cc8526ecbffedd3e68f156b0acbfb17e5cb9cd5d8ef388b3bb93169db
license    : GPL-2.0-only
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
