name       : gnome-mines
version    : 3.26.0
release    : 8
source     :
    - https://download.gnome.org/sources/gnome-mines/3.26/gnome-mines-3.26.0.tar.xz : 2b041eaf0d57307498c56d8e285b2e539f634fdba95d689f6af75aa4ed6edde9
license    : GPL-2.0
component  : games.puzzle
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-games-support-1)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
