name       : gnome-mines
version    : 3.18.2
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-mines/3.18/gnome-mines-3.18.2.tar.xz : 7e1e0778eb623bb96063944b0397503f964b898c234d30936c24ca1c9063f347
license    : GPL-2.0
summary    : Gnome Mine Field game
description: |
    Gnome Mine Field game
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(librsvg-2.0)
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
